version: '3'
services:
  mysql:
    container_name: $TOJ_DB_CONTAINER_NAME
    ports:
      - $TOJ_DB_PORT:3306
    build:
      context: $PWD
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=$TOJ_DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$TOJ_DB_NAME
    volumes:
      - $PWD/conf:/etc/mysql/conf.d
      - /Volumes/kitten/docker-volumes/$TOJ_DB_CONTAINER_NAME/mysql:/var/lib/mysql
